### ISSUE TITLE
2. As a user, I want to be able to navigate between the “list” view and the “add an item” view

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-8-smart-shopping-list#2]
This is 1 of 2 stories that should be completed in the first week to enable further development of the app.

AC:

* `react-router-dom` has been added as a project dependency
* 2 tabs are present and persistent at the bottom of the app: one for the “list” view, the other for the “add an item” view
* When a link is clicked, the browser URL updates to represent the current view
* Whichever tab is selected should indicate somehow that it is selected

**Comment by adriennefriend** [comment]
Hi @AliLynne and @abidishajia ! I was so thrilled to read this morning that you've already connected and have a plan for pairing. Seriously, made my day! 🤗  I hope it's a great experience.

I wanted to leave a comment here on the issue to remind you that it's a good idea to leave comments on the issue as you are planning and thinking through.

Comments help:
- **Your "future self"** ✔️ - comments create a record that you can look back at to see how you thought through a problem. This documentation is especially helpful in job interviews and other places where you're asked to talk about your work and how you think through problems.
- **You where you are right now** ✔️ - comments helps you get your thoughts, plans, and sketches out of your head and onto the page in some form, even if it's rough! 
- **Your Teammates!** ✔️ - CollabLab is all about collaboration, right, and the Issues you work fit together with issues being worked by the other pair. Making comments on your issue is another way of enhancing visibility about what you're working on! 

While totally not required, making notes on the Issue can be helpful for these reasons and more. Try it out and see if you find it useful! :tada: 💪

**Comment by adriennefriend** [comment]
Hey there @AliLynne and @abidishajia ! 

How's your collaboration been this week? If you have a moment, could you drop a few notes here about what you've been up to and how things are going? I'm also going to ask in Slack 🌈

**Comment by AliLynne** [comment]
- Had a bit of a snag when the react-router docs were down in solidarity w/ George Floyd, so we might want to double check those bits when the docs are back up.

- Looks like we've checked all the boxes for the AC.
